/*
    MXRPKAnswerVC.m
*/

@startuml
title PK答题
(*)  --> "开始答题"
--> "随机打乱用户题目顺序"
--> "准备显示下一题" as preShowNext
if "是否有下一题" then
    --> [YES] "显示该题题目"
    --> "随机[2-7]秒显示对手该题题目结果"
    if "随机时间是否到" then
    -> [YES] 显示对方该题答题结果
    --> === 答题汇总 ===
    else
    endif
    --> "答题倒计时20秒等待用户答题"
    if "答题时间到或者用户已经选好答案"
        --> [YES] 显示用户该题答题结果
    endif
    if "用户与对方都显示了答题结果"
        --> [YES] 等待1.5秒
        --> === 答题汇总 ===
    endif
    --> preShowNext
else
--> [NO] 提交答案
endif
--> (*)
@enduml

